---
label: Design Settings
hide_body: true
fields:
- name: primary_color
  type: color
  label: Background Color
  config:
    required: false
    color_format: Hex
  description: Adjust the background color
  default: "#B1BCBC"
- name: text_color
  type: color
  label: Text Color
  config:
    required: false
    color_format: Hex
  description: Enter text color
pages:
- themes/tale-theme/data/Settings.toml
